### PR TITLE
Bugfix/mongodb unsupported char

### PR DESCRIPTION
**Pull request by jonmassot**
A simple fix to remove unsupported char in the collection name. That will solve the [issue 53](https://github.com/OptimalBits/node_acl/issues/53).

### CODE REVIEW

**Comment by jonmassot** [comment]
This is a breaking change for all who are using MongoDB as the database. It'll invalidate all collections that are using the unsupported characters in mongodump, mainly the `/` and the `space`, but it could help solving the hassle of backing up all the ACL.

**Comment by manast** [comment]
Thanks. Will need to make a major upgrade and a notice about this on the README

**Comment by gitawego** [comment]
hope this can be merged

**Comment by jp** [comment]
@manast Do you have a plan for a major upgrade including this ?

**Comment by manast** [comment]
Its mostly that this is a breaking change and many users will have big problems if they have not configured correctly their package.json

**Comment by jp** [comment]
@manast I understand this issue, but if this is blocking will this bugfix never be merged?

**Comment by jonmassot** [comment]
I think the best way and maybe the only way to get this to be merged would be having a declarative to tell the module to use the correction or not and by default, it won't use it. Those that make sense?

**Comment by jp** [comment]
@jonmassot is making a good point there, @manast would you be ok with that?

**Comment by manast** [comment]
@jp either that or to implement this fix in a separate module such as the knex backend and others...

**Comment by wm-coco** [comment]
Just adding my two cents that I would love to see this included in the next version. A project of mine is currently having to deal with this issue, and I'd really rather not have to monkey-patch.

**Comment by leodutra** [comment]
Breaking changes deserve a major version. A non default optional should be used for easy update/port/migration.

**Comment by leodutra** [comment]
Update on https://github.com/OptimalBits/node_acl/pull/228

Merging master and introducing a fallback flag.

**Comment by Trenrod** [comment]
Will there be a v5.x or a 4.11? Current npm repo is still on 4.10 without this patch.

**Pull request merged**
