### PR TITLE
change req.url to req.originalUrl

### PR DESCRIPTION
**Pull request by danielrohers**
I'm using Express 4 and `req.url` does not work. Example:

```javascript
router.get('/', acl.middleware())
app.use('/blog', router)
```

`req.url` is '/' but my real url is '/blog'
where `req.originalUrl` equals '/blog'

### CODE REVIEW

**Comment by manast** [comment]
is this backwards compatible with express 1/2/3 ?

**Comment by danielrohers** [comment]
@manast

**Comment by gerardlopez** [comment]
Same situation here, @manast any plan to accept this PR?

**Comment by danielrohers** [comment]
@gerardlopez I'm using my fork with the fix on production and I have no more problems. I'm waiting to use the merge module again. @manast

**Comment by manast** [comment]
sorry for the late response, I have been quite busy lately :(

**Comment by jfgirard** [comment]
Wouldn't be better to have a option to use `req.url` vs `req.originalUrl` ?   Let's say i have an **admin** express app providing its routes and securing them with node ACL.  If I want to mount this app on `/admin` path of my main app, the rules are broken because the `req.originalUrl` include the mount url `/admin` where `req.url` won't.  Hence, using `req.url`, its easier to reuse express app. 


middleware( [numPathComponents, userId, permissions, **useOriginalUrl**] ) ?
 
I don't mind it default to `true` or `false` but having the option would ease my life ;-)

**Comment by ErikEvenson** [comment]
The documentation should be updated in the README.md from

```
The middleware will protect the resource named by req.url, pick the user from req.session.userId and check the permission for req.method, so the above would be equivalent to something like this:
```

to:

```
The middleware will protect the resource named by req.originalUrl, pick the user from req.session.userId and check the permission for req.method, so the above would be equivalent to something like this:
```

**Pull request merged**
