### PR TITLE
Fixed broken RegExp implementation

### PR DESCRIPTION
**Pull request by eightyfive**
Please consider merging this pull-request, it is non-breaking.

I fixed the broken RegExp implementation as explained here:
https://github.com/OptimalBits/node_acl/issues/30#issuecomment-154066640

### CODE REVIEW

**Comment by manast** [comment]
thanks for the improvement!

**Comment by eightyfive** [comment]
Hi, thanks for that.

Could you please also consider publishing the newer version of the package on `npm`?

Thanks.

**Comment by KrumBoychev** [comment]
Hi,

Could you please publish the latest version on npm, if possible?

BR

**Comment by piyushsf** [comment]
Is this published in new version?

**Comment by manast** [comment]
done!

**Pull request merged**
