### PR TITLE
Update mongodb-backend.js to create db index

### PR DESCRIPTION
**Pull request by devinea**
Add index create on resources collection. 
Speeds up performance where large numbers of resources are registered in ACL and called frequently.
Tests are passing.

### CODE REVIEW

**Comment by gitawego** [comment]
+1

**Comment by jrthib** [comment]
+1

**Comment by devinea** [comment]
@manast It would be great to get this merged. Is there anything else required?
Thanks

**Comment by manast** [comment]
sorry for the delay guys

**Comment by devinea** [comment]
thanks

**Pull request merged**
