### PR TITLE
don't call the cb twice in the same transaction

### PR DESCRIPTION
**Pull request by marbemac**
The async library complains if a callback is called twice in scope.

screen shot 2015-08-12 at 8 31 17 pm

### CODE REVIEW

**Comment by marbemac** [comment]
This also fixes #139.

**Comment by devinea** [comment]
@marbemac, Thanks for fixing

**Comment by kate008** [comment]
in acl module 0.4.8 it still through the same error

**Comment by Atinux** [comment]
Please update the version and publish on npm @manast 
:+1:

**Comment by manast** [comment]
done!

**Pull request merged**
